
version: '2'

services:
  magicspace:
    container_name: magicspace
    build: .
    volumes:
      - ./launches.json:/usr/share/nginx/html/launches.json:ro
    labels:
      - traefik.http.routers.magicspace.rule=Host(`space.magicorp.fr`)
    networks:
      - backend

networks:
  backend:
    name: backend
    external: true
